[package]
name = "tokio-i3ipc"
version = "0.3.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"
description = """
Bindings for i3 and tokio allowing async applications to communicate with i3 over
it's IPC interface. Contains futures implementations and convenience functions
for working with i3.
"""
categories = ["api-bindings", "asynchronous", "parsing", "gui"]
license = "MIT"
readme = "README.md"
keywords = ["i3", "ipc", "tokio", "async", "protocol"]
repository = "https://github.com/leshow/tokio-i3ipc"

[dependencies]
bytes = "0.4"
serde = "1.0"
serde_json = "1.0"
tokio-uds = "0.2"
tokio = "0.1"
futures = "0.1"
i3ipc-types = { version = "0.3", path = "i3ipc-types" }

[workspace]
members = ["./", "i3-ipc", "i3ipc-types"]

[[example]]
name = "subscribe"
path = "examples/subscribe.rs"

[[example]]
name = "manual_sub"
path = "examples/manual_sub.rs"